language: java

jdk: openjdk8

git:
  depth: false

before_install:
  - eval "$(ssh-agent -s)"
  - chmod 600 github_deploy_key test_key2
  - ssh-add github_deploy_key test_key2
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- mvn clean install -Pdependencies,openwis,admin -q
- mvn clean install -Puser -q

deploy:
  provider: script
  skip_cleanup: true
  script: sh maven_release.sh
  on:
    branch: master