language: java

jdk: openjdk8

git:
  depth: false

before_install:
  - openssl aes-256-cbc -K $encrypted_3e2d7896ecf2_key -iv $encrypted_3e2d7896ecf2_iv -in github_deploy_key.enc -out github_deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 github_deploy_key
  - ssh-add github_deploy_key
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
- mvn clean install -Pdependencies,openwis,admin -q
- mvn clean install -Puser -q

deploy:
  provider: script
  skip_cleanup: true
  script: sh maven_release.sh
  on:
    branch: master
